name: Build and release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for trusted publishing
      contents: read    
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup .NET 10
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          dotnet-version: 10.0.*

      - name: Restore dotnet
        run: dotnet restore

      - name: Build dotnet
        run: dotnet build --no-restore

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          flavor: |
            latest=false
          sep-tags: ";"
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Pack .NET project
        run: dotnet pack Intility.Logging.sln -o Intility.Logging/output --property:Version=${{ steps.meta.outputs.tags }}

      # Get a short-lived NuGet API key
      - name: NuGet login
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish to NuGet
        run: dotnet nuget push Intility.Logging/output/*.nupkg --skip-duplicate --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
